# Configuration for the 'local' profile (used for development on your local machine)
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/real_estate
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    dialect: org.hibernate.dialect.mysql5dialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: your_gmail_username
    password: your_gmail_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwtCookieName: cookie
  jwtSecret: secretKey
  jwtExpirationMs: 86400000

logging:
  level:
    org.springframework: ERROR

upload:
  dir: C:/Real-estate/angular-client/src/assets/photos
